# theme       : jekyll-theme-slate
title       : "Universal DB"
description : "Universal DB - A database of DS and 3DS homebrew"
repo        : "Universal-Team/db"
color       : "#072f4f"
image       : "https://raw.githubusercontent.com/Universal-Team/universal-team.net/master/images/icons/universal-team.png"

collections:
  3ds:
    output: true
  ds:
    output: true
