# theme       : jekyll-theme-slate
title       : "Universal DB"
description : "Universal DB - A database of DS and 3DS homebrew"
repo        : "Universal-Team/db"
color       : "#072f4f"
source      : _web
# This is dumb
url         : https://universal-team.github.io/db

collections:
  3ds:
    output: true
  ds:
    output: true
