# theme       : jekyll-theme-slate
title       : "Universal-DB"
description : "Universal-DB - A database of DS and 3DS homebrew"
repo        : "Universal-Team/db"
color       : "#1d8056"
image       : "https://universal-team.net/images/icons/universal-team.png"

sass:
  sass_dir: _sass

collections:
  3ds:
    output: true
  ds:
    output: true
