name: Update sources

# Run on push and hourly
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches: [ master ]
    paths: [ source/source.json, source/generate.py, .github/workflows/update.yml ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install python3 -y
        python3 -m pip install qrcode[pil] python-dateutil numpy

    - name: Delete old pages
      run: |
        rm -rf _3ds/* _ds/*

    - name: Run generate.py
      run: |
        export PATH=$PATH:/opt/devkitpro/tools/bin
        cd source
        python3 generate.py ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Update sources'
        force-add: 'false'
        files: .
        name: TWLBot
        email: flamekat54@aol.com 
