name: Update sources

# Run on push and hourly
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches: [ master ]
    paths: [ source/source.json, .github/workflows/update.yml ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install packages
      run: |
        pip3 install qrcode[pil] python-dateutil

    - name: Install tex3ds
      run: |
        curl -LO https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S tex3ds --noconfirm

    - name: Run generate.py
      run: |
        cd source
        python3 generate.py

    - name: Push changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Update sources'
        force-add: 'true'
        files: .
        name: TWLBot
        email: flamekat54@aol.com 
